name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: input
    id: version
    attributes:
      label: Origami Version
      description: What Origami version are you using?
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: What happened?
      description: Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Describe the expected behavior here.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the issue here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Trace
      description: Please provide output of the error.
    validations:
      required: false

  - type: checkboxes
    id: verified-not-exists
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and verified no issue exits for this problem.