[workspace]
name = "origami_examples"
version = "0.0.0"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
members = [
    "market",
    "projectile",
]

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.3.4" }
origami = { path = "../../origami" }