[package]
name = "random"
version = "0.0.0"
description = "A set of random mechanism for games"
homepage = "https://github.com/dojoengine/origami/tree/main/crates/random"

[dependencies]
dojo.workspace = true