name: Test

on: [push, pull_request]

env:
    DOJO_VERSION: v0.3.3

jobs:
  random:
    runs-on: ubuntu-latest
    name: Test random crate
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup@v1

      - name: Format
        run: scarb fmt --check

      - name: Build
        run: sozo build

      - name: Test
        run: sozo test